<script>
  // A demo section: the heading, the visual, a caption and the variants
  // generated by the plugin, printed straight from the `srcSet` export.
  let {
    title,
    caption,
    srcSet,
    children
  } = $props()
</script>

<section class="demo">
  <h2>{title}</h2>
  {@render children()}
  <p class="caption">{caption}</p>
  <ul class="variants">
    {#each srcSet as variant (variant.id)}
      <li>{variant.id} - {variant.width}w - {variant.url}</li>
    {/each}
  </ul>
</section>
